### ISSUE TITLE
Can not create a new application (Rails 5.1.0)

### ISSUE THREAD

**Issue by denegny** [thredded/thredded_create_app#11]
``` ruby
bundle install --quiet
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    rails (~> 5.1.0) was resolved to 5.1.0, which depends on
      actionpack (= 5.1.0)

```

**Comment by glebm** [comment]
Looks like the culprit is the `roadie-rails` dependency:

```
    roadie-rails was resolved to 1.0.5, which depends on
      railties (< 4.3, >= 3.0)
```

There is already a PR in review fixing this: https://github.com/Mange/roadie-rails/pull/69

**Comment by denegny** [comment]
It's very sad that in the production there are such raw tools, I wanted to write about your product in my blog, but you'll probably have to wait (((

**Comment by glebm** [comment]
> It's very sad that in the production there are such raw tools

It's up to all of us to fix that ;)

**Comment by glebm** [comment]
You can now use the following workaround:

```
thredded_create_app --rails-version=5.0.2 myapp
```

**Comment by denegny** [comment]
very nice decision

**Comment by glebm** [comment]
Now works on Rails 5.1

**Comment by denegny** [comment]
Thank you very much)
