### ISSUE TITLE
Bundler dependency? (may be due to specific-install?)

### ISSUE THREAD

**Issue by timdiggins** [thredded/thredded_create_app#2]
When trying this out with specific-install, then following instructions, I get a missing bundler† because of https://github.com/thredded/thredded_create_app/blob/master/exe/thredded_create_app#L7 (NB: I don't have bundler installed in my base gemset)

If install bundler into my gemset and re-run I'm then prompted to bundle install

Is it just a case of removing `require 'bundler/setup'` when running as a gem (not in dev)?

* †missing bundler: `/Users/tim/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)`

**Comment by glebm** [comment]
Good catch! Should be fixed with the above
